services:
  ros_base:
    image: custom_ros_humble
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - .:/root/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: "host"
    ipc: "host"
    pid: "host"
    # Build workspace, then launch TurtleBot3 simulation
    command: >
      bash -c "
        cd /root/ros2_ws &&
        colcon build --packages-select turtlebot3_simulation &&
        source install/setup.bash &&
        ros2 launch turtlebot3_simulation turtlebot3_simulation.launch.py
      "

  rviz2:
    image: custom_ros_humble
    depends_on:
      - ros_base
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - .:/root/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: "host"
    ipc: "host"
    pid: "host"
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        source /root/ros2_ws/install/setup.bash &&
        sleep 8 &&
        rviz2 -d /root/ros2_ws/src/turtlebot3_simulation/rviz/turtlebot3_view.rviz
      "


